language: c
sudo: required
dist: trusty

install:
  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - sudo apt-get install -y openresty libssl-dev
  - (wget http://luarocks.org/releases/luarocks-2.0.13.tar.gz; tar -xzf luarocks-2.0.13.tar.gz; cd luarocks-2.0.13/; ./configure --prefix=/usr/local/openresty/luajit --with-lua=/usr/local/openresty/luajit/ --lua-suffix=jit --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1; make; sudo make install)
  - sudo /usr/local/openresty/luajit/bin/luarocks install kong OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu/
  - sudo /usr/local/openresty/luajit/bin/luarocks install busted
  - git clone https://github.com/Mashape/kong.git kongapp
  - sudo ln -s /usr/local/openresty/nginx/sbin/nginx /usr/bin/nginx
  - export LUA_PATH="$LUA_PATH;`pwd`/?.lua;;"
  - export KONG_DATABASE=cassandra
  - export KONG_NGINX_DAEMON=true
  - export KONG_CUSTOM_PLUGINS=consumer-rate-limiting
  
script:
  - (cd kongapp; ./bin/busted ../spec/consumer-rate-limiting/00-unit_spec.lua)
